# Generated by Django 3.0.5 on 2024-05-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20240523_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
